export const LOAD_POSTS_ERROR = "LOAD_POSTS_ERROR"
export const LOAD_POSTS_LOADING = "LOAD_POSTS_LOADING"
export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS"

export const LOAD_USER_ERROR = "LOAD_USER_ERROR"
export const LOAD_USER_LOADING = "LOAD_USER_LOADING"
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"

export const LOAD_POST_ERROR = "LOAD_POST_ERROR"
export const LOAD_POST_LOADING = "LOAD_POST_LOADING"
export const LOAD_POST_SUCCESS = "LOAD_POST_SUCCESS"

export const LOAD_ALBUMS_ERROR = "LOAD_ALBUMS_ERROR"
export const LOAD_ALBUMS_LOADING = "LOAD_ALBUMS_LOADING"
export const LOAD_ALBUMS_SUCCESS = "LOAD_ALBUMS_SUCCESS"

export const LOAD_ALBUM_ERROR = "LOAD_ALBUM_ERROR"
export const LOAD_ALBUM_LOADING = "LOAD_ALBUM_LOADING"
export const LOAD_ALBUM_SUCCESS = "LOAD_ALBUM_SUCCESS"

export const SIGNIN_ERROR = "SIGNIN_ERROR"
export const SIGNIN_LOADING = "SIGNIN_LOADING"
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS"

export const EDIT_PROFILE_ERROR = "EDIT_PROFILE_ERROR"
export const EDIT_PROFILE_LOADING = "EDIT_PROFILE_LOADING"
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS"

export const LOAD_USER_POSTS_ERROR = "LOAD_USER_POSTS_ERROR"
export const LOAD_USER_POSTS_LOADING = "LOAD_USER_POSTS_LOADING"
export const LOAD_USER_POSTS_SUCCESS = "LOAD_USER_POSTS_SUCCESS"

export const LOAD_USER_ALBUMS_ERROR = "LOAD_USER_ALBUMS_ERROR"
export const LOAD_USER_ALBUMS_LOADING = "LOAD_USER_ALBUMS_LOADING"
export const LOAD_USER_ALBUMS_SUCCESS = "LOAD_USER_ALBUMS_SUCCESS"
